### ISSUE TITLE
no work in armv5

### ISSUE THREAD

**Issue by AdminHcat** [moparisthebest/static-curl#3]
curl 7.24.0 (arm-mv5sft-linux-gnueabi) libcurl/7.24.0 OpenSSL/0.9.8v zlib/1.2.5

Is there a compiled file suitable for the armv5 platform? I try to use armv7. It doesn't work

**Comment by moparisthebest** [comment]
@AdminHcat I added an armhf binary you could try https://github.com/moparisthebest/static-curl/releases/download/v7.81.0/curl-armhf

but without more work I can really only support architectures supported by multiarch/alpine https://github.com/moparisthebest/self-ci/blob/master/c/build.sh#L34

**Comment by moparisthebest** [comment]
This is officially linked in the readme now https://github.com/moparisthebest/static-curl/releases/latest/download/curl-armhf and will be built every release
